### PR TITLE
Add Ataccama to the companies list

### PR DESCRIPTION
**Pull request by iakovmarkov**
Adds or updates the following events or companies:
 - Ataccama

### Company updates
 - [x] I have put the most recent relevant date in the "Last Update" column
 - [N/A] I have linked to the article about the change, not the company's website (Please put N/A if there is no public post)

### CODE REVIEW

**Comment by drewbrew** [comment]
Looks like you have a merge conflict that GitHub won't let me fix. Would you mind taking care of it?

Thanks!

**Comment by drewbrew** [comment]
Looks like you have a merge conflict that GitHub won't let me fix. Would you mind taking care of it?

Thanks!

**Comment by iakovmarkov** [comment]
@drewbrew done!

**Comment by drewbrew** [comment]
Thanks!

**Pull request merged**
