### PR TITLE
Add Modern Health

### PR DESCRIPTION
**Pull request by nortronthered**
Adds the following events or companies:
 - Modern Health

The mandatory WFH policy was communicated internally, so we do not have an external link to provide.

### Checklist

 - [x] I have updated the event or company counts
 - [x] I have put the most recent relevant date in the "Last Update" column
 - [] I have linked to the article about the change, not the company's website

### CODE REVIEW

**Comment by phildini** [comment]
Hi there! We recently re-worked the site to use yaml data files. We'd be happy to accept your PR once it's been reworked to use the right format.

Thanks!

**Comment by nortronthered** [comment]
Hi @phildini!  Just adjusted it.  How does that look?

**Comment by nortronthered** [comment]
Updated, merge conflict should no longer be an issue

**Comment by nortronthered** [comment]
Updated again to resolve new merge conflicts

**Pull request merged**
