### PR TITLE
Apply split, with author info

### PR DESCRIPTION
**Pull request by toothbrush**
# Description

Apologies for the back and forth, but this is a clean branch that applies the split, retaining best-effort author info.

This supersedes #853.

### CODE REVIEW

**Comment by toothbrush** [comment]
This closes #670.

**Comment by toothbrush** [comment]
cc @drewbrew and @phildini

**Comment by toothbrush** [comment]
We'll also want to update the README with instructions for creating a company file.  Happy to do that.

**Comment by toothbrush** [comment]
I caught a bug and fixed it in https://github.com/phildini/stayinghomeclub/pull/864/commits/b3ea5ead5744d06fac0c19cdfe431a194c6f8bbb.  Turns out that `sort_natural` doesn't work without a specific field to sort on.  Thankfully, sorting on filename (which `| sort` does, because the first array element is the yaml filename) works because we downcased all the filenames before.

**Comment by phildini** [comment]
@toothbrush @drewbrew this was a monumental effort, and thanks to both of you for your efforts here.

To the end of merge conflicts! 🎉

**Comment by toothbrush** [comment]
> @toothbrush @drewbrew this was a monumental effort, and thanks to both of you for your efforts here.
> 
> To the end of merge conflicts! 🎉

And thank you to @con-cat for the behind-the-scenes work on the Git author info!  Credit where it's due 👌

**Comment by drewbrew** [comment]
Cheers to all three of you! Thanks for merging while I was asleep.

**Pull request merged**
