### PR TITLE
add status for test IO

### PR DESCRIPTION
**Pull request by DiamonDiva**
Adds the following events or companies:
 - test IO
 - 

### Checklist

 - [x] I have updated the event or company counts
 - [x] I have put the most recent relevant date in the "Last Update" column
 - [ ] I have linked to the article about the change, not the company's website

### CODE REVIEW

**Comment by DiamonDiva** [comment]
and apparently remove a lot of hanging white spaces...

**Comment by drewbrew** [comment]
It looks like you have a massive merge conflict thanks to that whitespace removal. I'll do a separate PR removing all the whitespace, then that *should* make your life a little easier.

**Comment by DiamonDiva** [comment]
appreciate it, sorry i wasn't more present when you pointed out the conflict!

**Comment by drewbrew** [comment]
No worries!

**Pull request merged**
