### PR TITLE
Update companies.yml

### PR DESCRIPTION
**Pull request by lintqueen**
Deleted redhat (duplicate entry, should have a space); corrected entry for Red Hat, which is now required WFH (and added new reference URL)

Adds or updates the following companies, events, or universities:
 - 
 - 

#### Company updates
 - [x] I have put the most recent relevant date in the "Last Update" column
 - [x] I have linked to the article about the change, not the company's homepage (Please put N/A if there is no public post)

#### Event updates
 - [ ] I have linked to the article about the change, not the event's homepage

#### University updates
 - [ ] I have linked to the article about the change, not the university's homepage

### CODE REVIEW

**Comment by lintqueen** [comment]
(duplicate of previous comment -- you can ignore, I think, but the boxes are checked!)

**Comment by drewbrew** [comment]
Is this a duplicate of https://github.com/phildini/stayinghomeclub/pull/841?

**Comment by krishnatre-siddhartha** [comment]
Trying to understand if #841 and #840 are same but done twice! 
@drewbrew could we close both #840 and #841 as Red Hat is taken care of at red-hat.yml

**Comment by drewbrew** [comment]
Closing as a duplicate just like #841.

**Pull request closed without merging**
