### PR TITLE
Adds Ro

### PR DESCRIPTION
**Pull request by cheshireoctopus**
Adds the following events or companies:
 - Ro

### Checklist
 - [x] I have put the most recent relevant date in the "Last Update" column
- [N/A] I have linked to the article about the change, not the company's website (Please put N/A if there is no public post)

### CODE REVIEW

**Comment by drewbrew** [comment]
Do you have a public-facing post by chance?

**Comment by phildini** [comment]
Hi there! We recently re-worked the site to use yaml data files. We'd be happy to accept your PR once it's been reworked to use the right format.

Thanks!

**Comment by cheshireoctopus** [comment]
@drewbrew - we do not have a public-facing post.

@phildini - will rework with the correct yaml format.

**Comment by cheshireoctopus** [comment]
@phildini - have reworked with the yaml format

**Pull request merged**
